##-- Experiment info exp_run_config --##
# experiment name. Keep it unique.
exp_name: exp006_1000epoch-ucf101


##-- Load saved model exp_run_config --##
# if this exp need to load a saved model: 1
# if this exp doesn't need to load a saved model: 0
is_using_saved_model: 0
# Path of saved model. Should be a '.hdf5' file.
saved_model_path: data/checkpoints/-.hdf5


##-- Dataset exp_run_config --##
# the path of the index csv file of the used data (like UCF101's csv file).
# The original file is : 'ucf101.csv'
data_csv_path: data/ucf101.csv


##-- Model exp_run_config --##
model: c3d
batch_size: 32
seq_length: 40
max_epoch: 1000
patients: 1000

